### ISSUE TITLE
Remove "Go isn't an option on Lamda" from /skillserver README

### ISSUE THREAD

**Issue by BHunter2889** [mikeflynn/go-alexa#51]
Not sure when this project was originally started but unless I'm missing something, this should be removed. I'm using an AWS provided library `aws-lambda-go` in conjunction with this package in mine. As a side note, I'm using Serverless to automate the deployment of my Go function to lambda, maybe worth adding this.

**Comment by mikeflynn** [comment]
Yes, this project outdates the time when AWS officially supported Go in Lambda but good note as I forgot that mention was in there. I've updated the README.md to reflect that change.
