### ISSUE TITLE
Broken under Go 1.7 

### ISSUE THREAD

**Issue by georgevanburgh** [mikeflynn/go-alexa#7]
Go 1.7 effectively deprecates `gorilla/context` - as per https://github.com/gorilla/context/issues/32. 

`gorilla/mux` and other gorilla projects have already migrated to using the new [standard library context package](http://golang.org/pkg/context) - which effectively means packages cannot mix their use of `gorilla/mux` and `gorilla/context`, as `go-alexa` currently does. Under Go 1.7, I get a on [skillserver.go#L62](https://github.com/mikeflynn/go-alexa/blob/f455f0c905f6967cc4b3147c5ad122e82fb66031/skillserver/skillserver.go#L62), as `context.Get(r, "echoRequest")` returns `nil`.

**Comment by mikeflynn** [comment]
Ugh. Compiles fine, but craps the bed in practice.

Looking at your pull request and it looks great and it's really a pretty small change, but I'm also unsure how to handle people using pre-1.7.

I guess we can merge in and then put a notice that you need 1.7 as of today.

**Comment by georgevanburgh** [comment]
The only semi-graceful alternative I can think of would be to abstract out
the context logic, and have two separate implementations - one for pre-1.7
(using gorilla context), and one for post (using native context), with a
conditional build tag choosing which version to include at compile time. I
guess it depends how important supporting pre-1.7 clients is to you

**Comment by mikeflynn** [comment]
Because of Go's no-breaking changes policy, 1.7 should be a simple upgrade for anyone. I don't think it's terrible to "require" (obviously you can't really require it with the way `go get` works) 1.7.

I'll merge and add a note to the README.

**Comment by mikeflynn** [comment]
Change merged in and README updated about the 1.7 requirement.

It's been a ridiculously crazy few weeks so thank you for the heads up and patch as I totally missed this!
